function createtextarrow(figure1)
%CREATETEXTARROW(FIGURE1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 20-Nov-2015 16:12:04

% Create textarrow
annotation(figure1,'textarrow',[0.502092050209205 0.518828451882844],...
    [0.684838160136286 0.517887563884157],...
    'String',{'Parameter updating starts here'},...
    'FontSize',14);

